### ISSUE TITLE
Example to serialize objects with optional properties

### ISSUE THREAD

**Issue by hastebrot** [oramasearch/seqproto#4]
If I have an object with property of type `string | undefined`, I would probably serialize it as 

in case of `string`: 
```js
ser.serializeBoolean(false); // for "is undefined"
ser.serializeString("text");
```

in case of `undefined`:
```js
ser.serializeBoolean(true); // for "is undefined"
ser.serializeString(""); // some default value

```

this allows me to use the boolean to decide wether to deserialize the object property back to `"text"` or `undefined`.

**Comment by allevo** [comment]
Hi!
For now, `seqproto` doesn't allow you to do that through a dedicated method. As you pointed out, the feature you need is achievable using a boolean flag to remember if the value is set or not.

For instance (not tested):
```ts
function serializeOptionalString(ser: Ser, str: string | undefined) {
  const isSet = str === undefined
  ser.serializeBoolean(isSer)
  if (isSer) {
    ser.serializeString(str!)
  }
}
function deserializeOptionalString(des: Des): string | undefined {
  const isSet = des.deserializeBoolean()
  if (!isSet) {
    return undefined
  }
  return des.deserializeString()
}
```

In this way, seqproto helps you record whether the value is set. The above code also differentiates an empty string from an undefined one, paying 1 byte of length.
Will the above code work for you?

You can treat undefined as an empty string if you don't need that distinction. In that case, you don't even pay the extra byte cost.

**Comment by hastebrot** [comment]
Yeah, this looks very good. I also like the explicit nature of the code.

**Comment by allevo** [comment]
I'm closing this issue. If there's something else, please open a new one.
